import { useEffect, useMemo, useState } from "react";
import { Link as RouterLink, useSearchParams } from "react-router-dom";
import Alert from "@mui/material/Alert";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import CircularProgress from "@mui/material/CircularProgress";
import Divider from "@mui/material/Divider";
import GlobalStyles from "@mui/material/GlobalStyles";
import Stack from "@mui/material/Stack";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import ToggleButton from "@mui/material/ToggleButton";
import ToggleButtonGroup from "@mui/material/ToggleButtonGroup";
import Typography from "@mui/material/Typography";
import { alpha } from "@mui/material/styles";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import PrintOutlinedIcon from "@mui/icons-material/PrintOutlined";

import { useReviewer } from "@/features/review/ReviewerContext";
import { api } from "@/shared/api/client";
import { currency, humanize, isoDate, shortDate } from "@/shared/format";
import type { Alert as AlertType, Overview, ReviewItem } from "@/shared/types";

const PENDING = "pending_review";

type Audience = "internal" | "customer";

/** Print rules. The screen keeps its chrome; the page drops all of it. */
const printStyles = (
  <GlobalStyles
    styles={{
      "@media print": {
        "@page": { margin: "14mm" },
        ".no-print": { display: "none !important" },
        body: { background: "#fff !important" },
        // Each finding starts its own page so an appendix can be detached and
        // handed over on its own.
        ".report-finding": { breakBefore: "page", breakInside: "avoid" },
        ".report-finding:first-of-type": { breakBefore: "auto" },
        ".report-evidence": { breakInside: "avoid" },
        ".report-part": { breakBefore: "page" },
        ".report-insight": { breakInside: "avoid" },
        // thead repeats on every printed page. It is the only reliable way to
        // put a running banner on each sheet of Part 2 -- a page pulled out of
        // a stack has to say what it is without the pages around it.
        ".running-banner": { display: "table-header-group" },
        a: { textDecoration: "none", color: "inherit" },
      },
    }}
  />
);

function Provenance({
  overview,
  alerts,
  severity,
  audience,
  reviewer,
  total,
  withheld,
}: {
  overview: Overview | null;
  alerts: AlertType[];
  severity: string;
  audience: Audience;
  reviewer: string;
  total: number;
  withheld: number;
}) {
  const versions = Array.from(new Set(alerts.map((a) => a.rule_version).filter(Boolean)));
  const rows: Array<[string, string]> = [
    ["Data as of", isoDate(overview?.as_of_date ?? null)],
    ["Generated", new Date().toLocaleString()],
    ["Generated by", reviewer],
    ["Rule version", versions.join(", ") || "unknown"],
    ["Severity filter", severity === "all" ? "none — complete queue" : severity],
    [
      "Findings included",
      alerts.length === total
        ? `${alerts.length} (complete governed queue)`
        : `${alerts.length} of ${total} (filtered view)`,
    ],
    ["Audience", audience === "customer" ? "Customer-facing packet" : "Internal review copy"],
  ];
  if (audience === "customer") {
    rows.push([
      "Evidence withheld",
      withheld === 0
        ? "none"
        : `${withheld} quote${withheld === 1 ? "" : "s"} pending review — not included`,
    ]);
  }

  return (
    <Box
      sx={{
        border: 1,
        borderColor: "divider",
        borderRadius: 1,
        p: 2,
        mb: 3,
        display: "grid",
        gap: 0.75,
        gridTemplateColumns: { xs: "1fr", sm: "repeat(2, minmax(0, 1fr))" },
      }}
    >
      {rows.map(([label, value]) => (
        <Stack key={label} direction="row" spacing={1.5} justifyContent="space-between">
          <Typography variant="caption" color="text.secondary" sx={{ whiteSpace: "nowrap" }}>
            {label}
          </Typography>
          <Typography variant="caption" sx={{ fontWeight: 600, textAlign: "right" }}>
            {value}
          </Typography>
        </Stack>
      ))}
    </Box>
  );
}

function Finding({ alert, audience }: { alert: AlertType; audience: Audience }) {
  const shown =
    audience === "customer"
      ? alert.evidence.filter((e) => e.review_status !== PENDING)
      : alert.evidence;
  const withheld = alert.evidence.length - shown.length;

  return (
    <Box component="section" className="report-finding" sx={{ mb: 4 }}>
      <Divider sx={{ mb: 2 }} />

      <Typography variant="overline" color="text.secondary">
        {alert.severity} · {humanize(alert.risk_class)} · score{" "}
        {alert.priority_score.toFixed(2)}
      </Typography>
      <Typography variant="h2" sx={{ fontSize: "1.25rem", mt: 0.5 }}>
        {alert.title}
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
        {alert.customer_name ?? alert.facility_id}
        {alert.facility_name ? ` · ${alert.facility_name}` : ""}
        {alert.system_label ? ` · ${alert.system_label}` : ""}
        {alert.acv_usd != null ? ` · ${currency(alert.acv_usd)}/yr` : ""}
      </Typography>

      <Typography variant="subtitle2" sx={{ mt: 2 }}>
        Why this is flagged
      </Typography>
      <Typography variant="body2">{alert.why}</Typography>

      <Typography variant="subtitle2" sx={{ mt: 1.5 }}>
        What it costs to wait
      </Typography>
      <Typography variant="body2">{alert.consequence}</Typography>

      <Typography variant="subtitle2" sx={{ mt: 1.5 }}>
        Evidence
      </Typography>
      {shown.length === 0 && (
        <Typography variant="body2" color="text.secondary">
          No approved supporting quotes.
        </Typography>
      )}
      <Stack spacing={0.75} sx={{ mt: 0.5 }}>
        {shown.map((evidence) => (
          <Box key={evidence.evidence_id} className="report-evidence">
            <Typography variant="body2" className="quote">
              &ldquo;{evidence.quote}&rdquo;
            </Typography>
            <Typography variant="caption" color="text.secondary">
              {evidence.source_file ?? "source unrecorded"}
              {evidence.authored_on ? ` · ${shortDate(evidence.authored_on)}` : ""}
              {audience === "internal"
                ? ` · ${evidence.review_status.replace("_", " ")}`
                : ""}
            </Typography>
          </Box>
        ))}
      </Stack>

      {withheld > 0 && (
        <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: "block" }}>
          {withheld} further quote{withheld === 1 ? "" : "s"} supporting this finding{" "}
          {withheld === 1 ? "is" : "are"} awaiting reviewer approval and{" "}
          {withheld === 1 ? "has" : "have"} been withheld from this packet.
        </Typography>
      )}

      <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: "block" }}>
        Observed {shortDate(alert.first_observed)} to {shortDate(alert.last_observed)}
        {alert.rule_version ? ` · judged under ${alert.rule_version}` : ""}
        {alert.owner ? ` · owner ${alert.owner}` : ""}
      </Typography>
    </Box>
  );
}

function PendingInsight({ item }: { item: ReviewItem }) {
  return (
    <Box className="report-insight" sx={{ mb: 2.5 }}>
      <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" useFlexGap>
        <Typography variant="overline" color="text.secondary">
          {humanize(item.insight_type)}
        </Typography>
        <Typography variant="caption" sx={{ fontWeight: 700 }}>
          {Math.round(item.confidence_score * 100)}% confidence
        </Typography>
        <Typography variant="caption" color="text.secondary">
          · {item.provenance === "ai" ? "model-proposed" : "rule-extracted"} (
          {item.extractor})
        </Typography>
      </Stack>
      <Typography variant="body2" sx={{ fontWeight: 600 }}>
        {item.summary}
      </Typography>
      <Typography variant="body2" className="quote" sx={{ mt: 0.5 }}>
        &ldquo;{item.quote}&rdquo;
      </Typography>
      <Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 0.5 }}>
        {[
          item.customer_name,
          item.facility_name,
          item.system_id,
          item.author,
          item.authored_on ? shortDate(item.authored_on) : null,
          item.source_file,
        ]
          .filter(Boolean)
          .join(" · ")}
        {item.days_overdue != null ? ` · ${item.days_overdue} days overdue` : ""}
      </Typography>
    </Box>
  );
}

function PendingPart({ items }: { items: ReviewItem[] }) {
  return (
    <Box className="report-part" component="section" sx={{ mt: 5 }}>
      {/*
        A table purely so the banner lands in a thead and repeats on every
        printed page. Part 2 must never be readable as governed findings, and
        on paper the only context a page carries is what is printed on it.
      */}
      <Box component="table" sx={{ width: "100%", borderCollapse: "collapse" }}>
        <Box component="thead" className="running-banner">
          <Box component="tr">
            <Box
              component="th"
              sx={{
                textAlign: "left",
                p: 1,
                border: 1,
                borderColor: "warning.main",
                bgcolor: (theme) => alpha(theme.palette.warning.main, 0.12),
              }}
            >
              <Typography variant="overline" sx={{ fontWeight: 700, display: "block" }}>
                Part 2 — Pending review · not governed findings
              </Typography>
              <Typography variant="caption" color="text.secondary">
                Extracted from prose, awaiting human approval. These carry a
                confidence score, not a rule version.
              </Typography>
            </Box>
          </Box>
        </Box>
        <Box component="tbody">
          <Box component="tr">
            <Box component="td" sx={{ p: 0, pt: 2 }}>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                {items.length} item{items.length === 1 ? "" : "s"} awaiting
                review. The review queue has no severity and is not affected by
                the Part 1 filter, so this list is complete.
              </Typography>
              {items.map((item) => (
                <PendingInsight key={item.insight_id} item={item} />
              ))}
            </Box>
          </Box>
        </Box>
      </Box>
    </Box>
  );
}

/**
 * The printable report, and the source of the PDF.
 *
 * It is a route rather than a print stylesheet over the dashboard because the
 * dashboard hides most of what a report has to contain: 39 of 41 alert cards
 * start collapsed, and the queue sits behind a tab. A print sheet over that
 * produces a compliance document with its evidence folded away.
 */
export function ReportPage() {
  const [params] = useSearchParams();
  const severity = params.get("severity") ?? "all";
  const { reviewer } = useReviewer();

  const [audience, setAudience] = useState<Audience>(
    params.get("audience") === "customer" ? "customer" : "internal"
  );
  const [alerts, setAlerts] = useState<AlertType[] | null>(null);
  const [pending, setPending] = useState<ReviewItem[]>([]);
  const [overview, setOverview] = useState<Overview | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    // 20 evidence lines rather than the queue's 3: a report carries the whole
    // chain, not a card's worth of it.
    Promise.allSettled([api.alerts(500, 20), api.overview(), api.reviewQueue(500)]).then(
      ([alertResult, overviewResult, reviewResult]) => {
        if (!active) return;
        if (alertResult.status === "fulfilled") setAlerts(alertResult.value);
        else setError("Could not load the alert queue.");
        if (overviewResult.status === "fulfilled") setOverview(overviewResult.value);
        if (reviewResult.status === "fulfilled") setPending(reviewResult.value);
      }
    );
    return () => {
      active = false;
    };
  }, []);

  // Arriving from the Export menu means "print this", so open the dialog once
  // the document has actually rendered. Printing an empty shell is the classic
  // failure here.
  const autoPrint = params.get("print") === "1";
  useEffect(() => {
    if (!autoPrint || !alerts) return;
    const timer = window.setTimeout(() => window.print(), 350);
    return () => window.clearTimeout(timer);
  }, [autoPrint, alerts]);

  const filtered = useMemo(
    () =>
      severity === "all"
        ? (alerts ?? [])
        : (alerts ?? []).filter((a) => a.severity === severity),
    [alerts, severity]
  );

  const withheld = useMemo(
    () =>
      filtered.reduce(
        (sum, a) => sum + a.evidence.filter((e) => e.review_status === PENDING).length,
        0
      ),
    [filtered]
  );

  if (error) {
    return (
      <Box sx={{ p: 4 }}>
        <Alert severity="error">{error}</Alert>
      </Box>
    );
  }

  if (!alerts) {
    return (
      <Stack alignItems="center" sx={{ py: 10 }}>
        <CircularProgress />
      </Stack>
    );
  }

  return (
    <Box sx={{ maxWidth: 940, mx: "auto", px: 3, py: 3 }}>
      {printStyles}

      <Stack
        className="no-print"
        direction="row"
        spacing={1.5}
        alignItems="center"
        flexWrap="wrap"
        useFlexGap
        sx={{ mb: 3 }}
      >
        <Button component={RouterLink} to="/" size="small" startIcon={<ArrowBackIcon />}>
          Back to dashboard
        </Button>
        <Box sx={{ flex: 1 }} />
        <ToggleButtonGroup
          size="small"
          exclusive
          value={audience}
          onChange={(_, value) => value && setAudience(value)}
          aria-label="Report audience"
        >
          <ToggleButton value="internal">Internal copy</ToggleButton>
          <ToggleButton value="customer">Customer packet</ToggleButton>
        </ToggleButtonGroup>
        <Button
          variant="contained"
          size="small"
          startIcon={<PrintOutlinedIcon />}
          onClick={() => window.print()}
        >
          Print / Save as PDF
        </Button>
      </Stack>

      {audience === "customer" && withheld > 0 && (
        <Alert severity="info" variant="outlined" className="no-print" sx={{ mb: 3 }}>
          {withheld} quote{withheld === 1 ? "" : "s"} still awaiting reviewer approval{" "}
          {withheld === 1 ? "is" : "are"} withheld from this packet. The count is stated in
          the document so the omission is visible rather than silent.
        </Alert>
      )}

      <Typography variant="h1" sx={{ fontSize: "1.6rem" }}>
        Governed alert report
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5, mb: 3 }}>
        Sego Industrial Water · water treatment compliance review
      </Typography>

      <Provenance
        overview={overview}
        alerts={filtered}
        severity={severity}
        audience={audience}
        reviewer={reviewer}
        total={alerts.length}
        withheld={withheld}
      />

      <Typography variant="h2" sx={{ fontSize: "1.1rem", mb: 1 }}>
        Summary
      </Typography>
      <Table size="small" sx={{ mb: 4 }}>
        <TableHead>
          <TableRow>
            <TableCell>Severity</TableCell>
            <TableCell>Finding</TableCell>
            <TableCell>Customer</TableCell>
            <TableCell>System</TableCell>
            <TableCell align="right">Score</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {filtered.map((alert) => (
            <TableRow key={alert.alert_id}>
              <TableCell sx={{ textTransform: "uppercase", fontSize: "0.7rem" }}>
                {alert.severity}
              </TableCell>
              <TableCell>{alert.title}</TableCell>
              <TableCell>{alert.customer_name ?? "—"}</TableCell>
              <TableCell>{alert.system_id ?? "—"}</TableCell>
              <TableCell align="right">{alert.priority_score.toFixed(2)}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>

      <Typography variant="h2" sx={{ fontSize: "1.1rem" }}>
        {audience === "internal" ? "Part 1 — Governed findings" : "Findings"}
      </Typography>
      {filtered.map((alert) => (
        <Finding key={alert.alert_id} alert={alert} audience={audience} />
      ))}

      {filtered.length === 0 && (
        <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
          No alerts match this filter.
        </Typography>
      )}

      {audience === "internal" && pending.length > 0 && <PendingPart items={pending} />}

      {audience === "customer" && pending.length > 0 && (
        <Typography variant="caption" color="text.secondary" sx={{ mt: 4, display: "block" }}>
          {pending.length} further item{pending.length === 1 ? "" : "s"} extracted
          from internal records {pending.length === 1 ? "is" : "are"} pending
          review and {pending.length === 1 ? "is" : "are"} not included in this
          packet.
        </Typography>
      )}
    </Box>
  );
}
