// GENERATED FILE -- do not edit by hand.
// Source: src/design-system/tokens/*.css (Material Theme Builder export).
// Regenerate with: pnpm run tokens

export type MaterialScheme = {
  primary: string;
  surfaceTint: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  background: string;
  onBackground: string;
  surface: string;
  onSurface: string;
  surfaceVariant: string;
  onSurfaceVariant: string;
  outline: string;
  outlineVariant: string;
  shadow: string;
  scrim: string;
  inverseSurface: string;
  inverseOnSurface: string;
  inversePrimary: string;
  primaryFixed: string;
  onPrimaryFixed: string;
  primaryFixedDim: string;
  onPrimaryFixedVariant: string;
  secondaryFixed: string;
  onSecondaryFixed: string;
  secondaryFixedDim: string;
  onSecondaryFixedVariant: string;
  tertiaryFixed: string;
  onTertiaryFixed: string;
  tertiaryFixedDim: string;
  onTertiaryFixedVariant: string;
  surfaceDim: string;
  surfaceBright: string;
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
};

export type SchemeName =
  | "light"
  | "lightMediumContrast"
  | "lightHighContrast"
  | "dark"
  | "darkMediumContrast"
  | "darkHighContrast";

export const schemes: Record<SchemeName, MaterialScheme> = {
  "darkHighContrast": {
    "primary": "#ebf0ff",
    "surfaceTint": "#aac7ff",
    "onPrimary": "#000000",
    "primaryContainer": "#a6c3fc",
    "onPrimaryContainer": "#000b20",
    "secondary": "#ebf0ff",
    "onSecondary": "#000000",
    "secondaryContainer": "#bac3d8",
    "onSecondaryContainer": "#030b1a",
    "tertiary": "#ffe9ff",
    "onTertiary": "#000000",
    "tertiaryContainer": "#d8b8dc",
    "onTertiaryContainer": "#16041d",
    "error": "#ffece9",
    "onError": "#000000",
    "errorContainer": "#ffaea4",
    "onErrorContainer": "#220001",
    "background": "#111318",
    "onBackground": "#e2e2e9",
    "surface": "#111318",
    "onSurface": "#ffffff",
    "surfaceVariant": "#44474e",
    "onSurfaceVariant": "#ffffff",
    "outline": "#eeeff9",
    "outlineVariant": "#c0c2cc",
    "shadow": "#000000",
    "scrim": "#000000",
    "inverseSurface": "#e2e2e9",
    "inverseOnSurface": "#000000",
    "inversePrimary": "#294878",
    "primaryFixed": "#d6e3ff",
    "onPrimaryFixed": "#000000",
    "primaryFixedDim": "#aac7ff",
    "onPrimaryFixedVariant": "#00112b",
    "secondaryFixed": "#dae2f9",
    "onSecondaryFixed": "#000000",
    "secondaryFixedDim": "#bec6dc",
    "onSecondaryFixedVariant": "#081121",
    "tertiaryFixed": "#fad8fd",
    "onTertiaryFixed": "#000000",
    "tertiaryFixedDim": "#ddbce0",
    "onTertiaryFixedVariant": "#1d0823",
    "surfaceDim": "#111318",
    "surfaceBright": "#4e5056",
    "surfaceContainerLowest": "#000000",
    "surfaceContainerLow": "#1d2024",
    "surfaceContainer": "#2e3036",
    "surfaceContainerHigh": "#393b41",
    "surfaceContainerHighest": "#45474c"
  },
  "darkMediumContrast": {
    "primary": "#cdddff",
    "surfaceTint": "#aac7ff",
    "onPrimary": "#002551",
    "primaryContainer": "#7491c7",
    "onPrimaryContainer": "#000000",
    "secondary": "#d4dcf2",
    "onSecondary": "#1d2636",
    "secondaryContainer": "#8891a5",
    "onSecondaryContainer": "#000000",
    "tertiary": "#f3d2f7",
    "onTertiary": "#331d39",
    "tertiaryContainer": "#a487a9",
    "onTertiaryContainer": "#000000",
    "error": "#ffd2cc",
    "onError": "#540003",
    "errorContainer": "#ff5449",
    "onErrorContainer": "#000000",
    "background": "#111318",
    "onBackground": "#e2e2e9",
    "surface": "#111318",
    "onSurface": "#ffffff",
    "surfaceVariant": "#44474e",
    "onSurfaceVariant": "#dadce6",
    "outline": "#afb2bb",
    "outlineVariant": "#8e9099",
    "shadow": "#000000",
    "scrim": "#000000",
    "inverseSurface": "#e2e2e9",
    "inverseOnSurface": "#282a2f",
    "inversePrimary": "#294878",
    "primaryFixed": "#d6e3ff",
    "onPrimaryFixed": "#00112b",
    "primaryFixedDim": "#aac7ff",
    "onPrimaryFixedVariant": "#133665",
    "secondaryFixed": "#dae2f9",
    "onSecondaryFixed": "#081121",
    "secondaryFixedDim": "#bec6dc",
    "onSecondaryFixedVariant": "#2e3647",
    "tertiaryFixed": "#fad8fd",
    "onTertiaryFixed": "#1d0823",
    "tertiaryFixedDim": "#ddbce0",
    "onTertiaryFixedVariant": "#452e4a",
    "surfaceDim": "#111318",
    "surfaceBright": "#43444a",
    "surfaceContainerLowest": "#06070c",
    "surfaceContainerLow": "#1b1e22",
    "surfaceContainer": "#26282d",
    "surfaceContainerHigh": "#313238",
    "surfaceContainerHighest": "#3c3e43"
  },
  "dark": {
    "primary": "#aac7ff",
    "surfaceTint": "#aac7ff",
    "onPrimary": "#0a305f",
    "primaryContainer": "#284777",
    "onPrimaryContainer": "#d6e3ff",
    "secondary": "#bec6dc",
    "onSecondary": "#283141",
    "secondaryContainer": "#3e4759",
    "onSecondaryContainer": "#dae2f9",
    "tertiary": "#ddbce0",
    "onTertiary": "#3f2844",
    "tertiaryContainer": "#573e5c",
    "onTertiaryContainer": "#fad8fd",
    "error": "#ffb4ab",
    "onError": "#690005",
    "errorContainer": "#93000a",
    "onErrorContainer": "#ffdad6",
    "background": "#111318",
    "onBackground": "#e2e2e9",
    "surface": "#111318",
    "onSurface": "#e2e2e9",
    "surfaceVariant": "#44474e",
    "onSurfaceVariant": "#c4c6d0",
    "outline": "#8e9099",
    "outlineVariant": "#44474e",
    "shadow": "#000000",
    "scrim": "#000000",
    "inverseSurface": "#e2e2e9",
    "inverseOnSurface": "#2e3036",
    "inversePrimary": "#415f91",
    "primaryFixed": "#d6e3ff",
    "onPrimaryFixed": "#001b3e",
    "primaryFixedDim": "#aac7ff",
    "onPrimaryFixedVariant": "#284777",
    "secondaryFixed": "#dae2f9",
    "onSecondaryFixed": "#131c2b",
    "secondaryFixedDim": "#bec6dc",
    "onSecondaryFixedVariant": "#3e4759",
    "tertiaryFixed": "#fad8fd",
    "onTertiaryFixed": "#28132e",
    "tertiaryFixedDim": "#ddbce0",
    "onTertiaryFixedVariant": "#573e5c",
    "surfaceDim": "#111318",
    "surfaceBright": "#37393e",
    "surfaceContainerLowest": "#0c0e13",
    "surfaceContainerLow": "#191c20",
    "surfaceContainer": "#1d2024",
    "surfaceContainerHigh": "#282a2f",
    "surfaceContainerHighest": "#33353a"
  },
  "lightHighContrast": {
    "primary": "#032b5b",
    "surfaceTint": "#415f91",
    "onPrimary": "#ffffff",
    "primaryContainer": "#2a497a",
    "onPrimaryContainer": "#ffffff",
    "secondary": "#232c3d",
    "onSecondary": "#ffffff",
    "secondaryContainer": "#41495b",
    "onSecondaryContainer": "#ffffff",
    "tertiary": "#3a2440",
    "onTertiary": "#ffffff",
    "tertiaryContainer": "#59405e",
    "onTertiaryContainer": "#ffffff",
    "error": "#600004",
    "onError": "#ffffff",
    "errorContainer": "#98000a",
    "onErrorContainer": "#ffffff",
    "background": "#f9f9ff",
    "onBackground": "#191c20",
    "surface": "#f9f9ff",
    "onSurface": "#000000",
    "surfaceVariant": "#e0e2ec",
    "onSurfaceVariant": "#000000",
    "outline": "#292c33",
    "outlineVariant": "#464951",
    "shadow": "#000000",
    "scrim": "#000000",
    "inverseSurface": "#2e3036",
    "inverseOnSurface": "#ffffff",
    "inversePrimary": "#aac7ff",
    "primaryFixed": "#2a497a",
    "onPrimaryFixed": "#ffffff",
    "primaryFixedDim": "#0e3262",
    "onPrimaryFixedVariant": "#ffffff",
    "secondaryFixed": "#41495b",
    "onSecondaryFixed": "#ffffff",
    "secondaryFixedDim": "#2a3344",
    "onSecondaryFixedVariant": "#ffffff",
    "tertiaryFixed": "#59405e",
    "onTertiaryFixed": "#ffffff",
    "tertiaryFixedDim": "#412a47",
    "onTertiaryFixedVariant": "#ffffff",
    "surfaceDim": "#b8b8bf",
    "surfaceBright": "#f9f9ff",
    "surfaceContainerLowest": "#ffffff",
    "surfaceContainerLow": "#f0f0f7",
    "surfaceContainer": "#e2e2e9",
    "surfaceContainerHigh": "#d3d4db",
    "surfaceContainerHighest": "#c5c6cd"
  },
  "lightMediumContrast": {
    "primary": "#133665",
    "surfaceTint": "#415f91",
    "onPrimary": "#ffffff",
    "primaryContainer": "#506da0",
    "onPrimaryContainer": "#ffffff",
    "secondary": "#2e3647",
    "onSecondary": "#ffffff",
    "secondaryContainer": "#646d80",
    "onSecondaryContainer": "#ffffff",
    "tertiary": "#452e4a",
    "onTertiary": "#ffffff",
    "tertiaryContainer": "#7f6484",
    "onTertiaryContainer": "#ffffff",
    "error": "#740006",
    "onError": "#ffffff",
    "errorContainer": "#cf2c27",
    "onErrorContainer": "#ffffff",
    "background": "#f9f9ff",
    "onBackground": "#191c20",
    "surface": "#f9f9ff",
    "onSurface": "#0f1116",
    "surfaceVariant": "#e0e2ec",
    "onSurfaceVariant": "#33363e",
    "outline": "#4f525a",
    "outlineVariant": "#6a6d75",
    "shadow": "#000000",
    "scrim": "#000000",
    "inverseSurface": "#2e3036",
    "inverseOnSurface": "#f0f0f7",
    "inversePrimary": "#aac7ff",
    "primaryFixed": "#506da0",
    "onPrimaryFixed": "#ffffff",
    "primaryFixedDim": "#375586",
    "onPrimaryFixedVariant": "#ffffff",
    "secondaryFixed": "#646d80",
    "onSecondaryFixed": "#ffffff",
    "secondaryFixedDim": "#4c5567",
    "onSecondaryFixedVariant": "#ffffff",
    "tertiaryFixed": "#7f6484",
    "onTertiaryFixed": "#ffffff",
    "tertiaryFixedDim": "#654c6b",
    "onTertiaryFixedVariant": "#ffffff",
    "surfaceDim": "#c5c6cd",
    "surfaceBright": "#f9f9ff",
    "surfaceContainerLowest": "#ffffff",
    "surfaceContainerLow": "#f3f3fa",
    "surfaceContainer": "#e7e8ee",
    "surfaceContainerHigh": "#dcdce3",
    "surfaceContainerHighest": "#d1d1d8"
  },
  "light": {
    "primary": "#415f91",
    "surfaceTint": "#415f91",
    "onPrimary": "#ffffff",
    "primaryContainer": "#d6e3ff",
    "onPrimaryContainer": "#284777",
    "secondary": "#565f71",
    "onSecondary": "#ffffff",
    "secondaryContainer": "#dae2f9",
    "onSecondaryContainer": "#3e4759",
    "tertiary": "#705575",
    "onTertiary": "#ffffff",
    "tertiaryContainer": "#fad8fd",
    "onTertiaryContainer": "#573e5c",
    "error": "#ba1a1a",
    "onError": "#ffffff",
    "errorContainer": "#ffdad6",
    "onErrorContainer": "#93000a",
    "background": "#f9f9ff",
    "onBackground": "#191c20",
    "surface": "#f9f9ff",
    "onSurface": "#191c20",
    "surfaceVariant": "#e0e2ec",
    "onSurfaceVariant": "#44474e",
    "outline": "#74777f",
    "outlineVariant": "#c4c6d0",
    "shadow": "#000000",
    "scrim": "#000000",
    "inverseSurface": "#2e3036",
    "inverseOnSurface": "#f0f0f7",
    "inversePrimary": "#aac7ff",
    "primaryFixed": "#d6e3ff",
    "onPrimaryFixed": "#001b3e",
    "primaryFixedDim": "#aac7ff",
    "onPrimaryFixedVariant": "#284777",
    "secondaryFixed": "#dae2f9",
    "onSecondaryFixed": "#131c2b",
    "secondaryFixedDim": "#bec6dc",
    "onSecondaryFixedVariant": "#3e4759",
    "tertiaryFixed": "#fad8fd",
    "onTertiaryFixed": "#28132e",
    "tertiaryFixedDim": "#ddbce0",
    "onTertiaryFixedVariant": "#573e5c",
    "surfaceDim": "#d9d9e0",
    "surfaceBright": "#f9f9ff",
    "surfaceContainerLowest": "#ffffff",
    "surfaceContainerLow": "#f3f3fa",
    "surfaceContainer": "#ededf4",
    "surfaceContainerHigh": "#e7e8ee",
    "surfaceContainerHighest": "#e2e2e9"
  }
} as const;
